/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vertexlabs_logging_natives_Win32ConsoleAPI */

#ifndef _Included_com_vertexlabs_logging_natives_Win32ConsoleAPI
#define _Included_com_vertexlabs_logging_natives_Win32ConsoleAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_BLACK
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_BLACK 0L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_BLUE
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_BLUE 1L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_GREEN
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_GREEN 2L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_AQUA
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_AQUA 3L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_RED
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_RED 4L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_PURPLE
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_PURPLE 5L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_YELLOW
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_YELLOW 6L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_WHITE
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_WHITE 7L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_GREY
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_GREY 8L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_BLUE
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_BLUE 9L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_GREEN
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_GREEN 10L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_AQUA
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_AQUA 11L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_RED
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_RED 12L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_PURPLE
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_PURPLE 13L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_YELLOW
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_YELLOW 14L
#undef com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_WHITE
#define com_vertexlabs_logging_natives_Win32ConsoleAPI_FOREGROUND_LIGHT_WHITE 15L
/*
 * Class:     com_vertexlabs_logging_natives_Win32ConsoleAPI
 * Method:    cls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vertexlabs_logging_natives_Win32ConsoleAPI_cls
  (JNIEnv *, jobject);

/*
 * Class:     com_vertexlabs_logging_natives_Win32ConsoleAPI
 * Method:    setCursorPosition
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_com_vertexlabs_logging_natives_Win32ConsoleAPI_setCursorPosition
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     com_vertexlabs_logging_natives_Win32ConsoleAPI
 * Method:    keepColors
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vertexlabs_logging_natives_Win32ConsoleAPI_keepColors
  (JNIEnv *, jobject);

/*
 * Class:     com_vertexlabs_logging_natives_Win32ConsoleAPI
 * Method:    restoreColors
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vertexlabs_logging_natives_Win32ConsoleAPI_restoreColors
  (JNIEnv *, jobject);

/*
 * Class:     com_vertexlabs_logging_natives_Win32ConsoleAPI
 * Method:    setColor
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_com_vertexlabs_logging_natives_Win32ConsoleAPI_setColor
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     com_vertexlabs_logging_natives_Win32ConsoleAPI
 * Method:    getch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vertexlabs_logging_natives_Win32ConsoleAPI_getch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
